
name: HaskellCI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-haskell@v1
      with:
        ghc-version: '8.6.5'
        cabal-version: '3.0'
    - name: Install dependencies
      run: |
        cabal update
    - name: Build
      run: |
        cabal configure --disable-coverage --disable-tests
        cabal new-build
    - name: Local Install 
      run: | 
        cabal new-install --lib
    - name: Run tests
      run: cabal new-test --enable-coverage