
name: HaskellCI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-haskell@v1
      with:
        ghc-version: '8.8.3'
        cabal-version: '3.2'
    - name: Install dependencies
      run: |
        cabal update
        cabal new-configure --enable-coverage --enable-tests
        cabal new-install --only-dependencies
    - name: Build
      run: |
        cabal new-build
    - name: Local Install 
      run: | 
        cabal new-install --lib
    - name: Run tests
      run: cabal new-test