name: Build on Push and PR

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        ghc: [ '8.6.5' ]
        cabal: [ '3.0' ]
    name: Cabal ${{ matrix.cabal }} new-test on ${{ matrix.ghc }}
    steps:
      - uses: actions/checkout@master
      - name: Setup Haskell
        uses: actions/setup-haskell@v1
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}
      - run: cabal new-test