name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Hi there! Thanks for opening an Issue! Feel free to @Twonki to make your issue more visible.'
        pr-message: 'Hi! Thanks for contributing! While the CI runs, please take some time and check if you have stick to the Contribution Guidelines! Your PR will shortly be looked at!'